### PR TITLE
Expand the GMTdataset to hold also attributes and BoundingBox fields.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by joa-quim** [comment]
@htyeim Just to warn you of this since you seem to *suffer* when I change any of the GMTtypes.

**Comment by htyeim** [comment]
Thanks! Actually I have encountered the problem of the change of `GMTdataset` last week 🤣. I tried to produce some timeline using GMT.jl, and I found this one https://discourse.julialang.org/t/how-to-plot-a-timeline/25095 . However, I could not reorganise the code very quickly and the work had to be done in a day, so at last I returned to use latex (tikz)...

**Comment by joa-quim** [comment]
But last real change of the GMTdataset type was in last April!
As with the other types the safest way of creating a ``GMTdataset`` is to use the ``mat2ds`` helper function.

**Comment by htyeim** [comment]
Yes, I think I should use the helper functions instead of formatting the data structure directly. Also I think I need to build a better habit of coding, because I found to reorganise my old code is a hard work even for me....

**Pull request merged**
