### PR TITLE
Do not save the gmt bin dir in deps.jl. Not used anymore.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by liming-he** [comment]
This package cannot be compiled without the file deps.jl
See error message below. Thanks.

julia> using GMT
[ Info: Precompiling GMT [5752ebe1-31b9-557e-87aa-f909b540aa54]
ERROR: LoadError: SystemError: opening file "/home/myusername/.julia/packages/GMT/1kBBX/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:168
  [2] #systemerror#62
    @ ./error.jl:167 [inlined]
  [3] systemerror

**Comment by joa-quim** [comment]
You are probably transitioning to the new GMT_jll system and something didn't go right. Please try
```
import Pkg; Pkg.build("GMT")
```

**Comment by liming-he** [comment]
Thanks. See new error message below. 

julia> import Pkg; Pkg.build("GMT")
    Building Conda → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/e32a90da027ca45d84678b826fffd3110bb3fc90/build.log`
    Building GMT ──→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/5968385e86d9c119db96d05e41df420c245f73da/build.log`

julia> using GMT
[ Info: Precompiling GMT [5752ebe1-31b9-557e-87aa-f909b540aa54]
ERROR: LoadError: SystemError: opening file "/home/liming/.julia/packages/GMT/1kBBX/deps/deps.jl": No such file or directory
Stacktrace:
  [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
    @ Base ./error.jl:168
  [2] #systemerror#62
    @ ./error.jl:167 [inlined]
  [3] systemerror
    @ ./error.jl:167 [inlined]
  [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing)
    @ Base ./iostream.jl:293
  [5] open
    @ ./iostream.jl:282 [inlined]
  [6] open(f::Base.var"#326#327"{String}, args::String; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:328
  [7] open
    @ ./io.jl:328 [inlined]
  [8] read
    @ ./io.jl:434 [inlined]
  [9] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./loading.jl:1166
 [10] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
 [11] include(x::String)
    @ GMT ~/.julia/packages/GMT/1kBBX/src/GMT.jl:1
 [12] top-level scope
    @ ~/.julia/packages/GMT/1kBBX/src/GMT.jl:34
 [13] include
    @ ./Base.jl:384 [inlined]
 [14] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1235
 [15] top-level scope
    @ none:1
 [16] eval
    @ ./boot.jl:360 [inlined]
 [17] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [18] top-level scope
    @ none:1
in expression starting at /home/liming/.julia/packages/GMT/1kBBX/src/GMT.jl:1
ERROR: Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to /home/liming/.julia/compiled/v1.6/GMT/jl_X8Vs6q.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1385
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1329
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1043
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:936
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:923

**Comment by joa-quim** [comment]
I don't know why it is failing to install GMT via Conda and that should be why the deps.jl file is not being created.

Next version will see a substantial change in the sense that it will install GMT via a GMT_jll artifact (no more Conda). What I suggest you to try is to install the master version with ``] add GMT#master``. I would rather not suggest users to use the master version but for your case that's what has more chances to solve the issue.

**Comment by liming-he** [comment]
This works. Thanks a lot.
Liming

**Pull request merged**
