### PR TITLE
Document the linestyles and Themes

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by joa-quim** [comment]
Hi @htyeim,

I forgot to ask you this in my previous PR and merged it in master so referring it here. Master has now themes and by default that theme is the GMT ``modern`` theme. Since you told me you always use ``modern`` scripts the change for you should be small, except for the fact that now ``FRAME_PEN`` (the Cartesian axes line thickness) is now 0.75p instead of the GMT default of 1.5p (which I find way too thick).

Please try master and say something if you find any troubles (had to do several gymnastics to make the modern mode work both for *modern* as well as *classic* scripts) .

**Comment by htyeim** [comment]
> Hi @htyeim,
> 
> I forgot to ask you this in my previous PR and merged it in master so referring it here. Master has now themes and by default that theme is the GMT `modern` theme. Since you told me you always use `modern` scripts the change for you should be small, except for the fact that now `FRAME_PEN` (the Cartesian axes line thickness) is now 0.75p instead of the GMT default of 1.5p (which I find way too thick).
> 
> Please try master and say something if you find any troubles (had to do several gymnastics to make the modern mode work both for _modern_ as well as _classic_ scripts) .

Many thanks! I am now trying to rewrite some examples of `GMT.jl` in modern mode. It might be easier for beginner to plot their figures by modifying gradually the code of examples in modern mode. 😄

**Comment by htyeim** [comment]
By the way, based on `GMT.jl`, I have finished a paper. In the Acknowledgement, I have pointed out all the figures are plotted by `gmt` and `GMT.jl`. Please check the paper https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021JA029209. The figures in the end of the pdf (https://onlinelibrary.wiley.com/share/author/RV4ZRIZXMWMUUQSDG9XI?target=10.1029/2021JA029209) are all plotted using `GMT.jl`. Many thanks for this great project!!

**Comment by joa-quim** [comment]
I'm curious why you think it's easier to a beginner to do
```
gmtbegin(...)
    command1(...)
    command1(...)
gmtend(...)
```
then, if plotting append a ``!`` to the command name 
```
command1(...)
command2!(...)
``

Regarding the figures of your paper, I would suggest that you do not annotate all four axes of the geographical figs like fig3, fig5, fig6. It makes it a bit too heavy. Also did you use the modern mode to plot them (either plain GMT or GMT.jl)? I'm asking this because  figs like fig6 have the frame a bit too wide. Modern mode in version 6.2 tries to scale frame width and annotations fonts in function of figure size. (GMT.jl master tries to do the same in either modern or classic).
You may also consider to cite GMT as in https://www.generic-mapping-tools.org/cite/ For GMT.jl I have a reference somewhere but since it's an AGU conference ref you may just leave at is. Thanks

**Comment by htyeim** [comment]
The paper has been proofed... it cannot be changed.. I will follow the citation next time.

I think the modern mode separate each step, and enclose the process of generating a figure using `gtmbegin()` and `gmtend()`. It might be easier for beginner to follow the steps and focused on the current figure. Anyway, different people have different styles. I may provide some plotting code in modern mode for some of the examples in document of `GMT.jl`.

**Comment by joa-quim** [comment]
Ok, no problems. I wish many _next times_
You can also create new examples.

**Pull request merged**
