### PR TITLE
test

### PR DESCRIPTION
**Pull request by htyeim**
Check the `mtime` of `gmt6.` directories  before delete them

### CODE REVIEW

**Comment by joa-quim** [comment]
Sorry, .gmt directory is not located in ``homedir()`` but what Windows call ``HOME`` or ``HOMEPATH``.
Just leave this open for a while. I'll look at it when I have more time. Meanwhile you know how to make it work for you.

**Comment by joa-quim** [comment]
I committed to master a version of your code but it's restricted to GMT6.1 because 6.0 has a bug on Windows that does not clear the ``sessions`` dir. I added a new option in GMT that prints the full path to the ``~/.gmt`` dir. However, I also found that GMT already has a test to delete a previous ``gmt.xxxx`` in case ``xxxx`` is the same as current session number so this all matter is probably not worth and may be removed in future.

**Comment by htyeim** [comment]
No problem. Thank you! Hope the new version of gmt would release soon~

**Comment by joa-quim** [comment]
For tho months that we keep saying it's for next week but thinks falling in the plate of fixes.

**Pull request closed without merging**
