### PR TITLE
Support Symbol Dict as -T argument

### LINKED ISSUE #1033: makecpt -T inconsistency
This works
```
makecpt(T="red,green,blue")
```
but this errors

```
makecpt(T=(:red,:green,:blue))
```

### PR DESCRIPTION
**Pull request by ZMAlt**
Hi @joa-quim , I am making a PR to fix #1033 . 
All tests passed.

### CODE REVIEW

**Review by joa-quim — APPROVED** [review]
Thanks.

**Comment by joa-quim** [comment]
BTW, I would be curious in some feed-back on how hard is to navigate the source code in order to find where changes need to go.

**Comment by ZMAlt** [comment]
It's not so hard for me because I have been following `GMT` and `GMT.jl`. Really appreciate your efforts on them!

**Comment by joa-quim** [comment]
Good.

**Pull request merged**
