### PR TITLE
Test if -flts-model=local-dynamic fix Linux CI failures.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by adigitoleo** [comment]
Since the GMT tests are passing it must be Julia that is failing, so this flag probably won't help. I'll soon be able to check on an Ubuntu machine to see if I can investigate further.

**Comment by joa-quim** [comment]
The error
> /opt/hostedtoolcache/julia/1.7.1/x64/bin/../lib/julia/libstdc++.so.6: cannot allocate memory

is coming from the ``libstdc`` that is shipped with Julia, and the one in that Linux VM had no problems because, as you say, the previous tests passed. One might think that Julia updated its ``libstdc`` and then things broke, but I tested with Julia 1.5 and it's still broken.

**Comment by joa-quim** [comment]
Closing this one as it auto-solved (???)

**Comment by adigitoleo** [comment]
Apologies, I wasn't able to track it down, hopefully it doesn't reappear...

**Comment by adigitoleo** [comment]
Well, I did not see it yet! That's nice, I had started to translate the GMT tutorials somewhere, maybe I can find that again. I haven't been making maps so much lately, I'm doing more modelling at the moment, but I do have some stuff from my last report that I can clean up for examples. Might take a little time, things got too busy this year.

**Comment by joa-quim** [comment]
Keep modeling :). 

The GMT tutorials (if you refer to gallery) tend to be more complex examples. Here I'm aiming for simplicity for the basic examples and a bit more elaborate one in the "Tutorials". The docs site is not yet in it's final destination and, even given that I _stole_ the look from Makie,  there are still many things that are not well organized (html and css is an horror).

**Pull request closed without merging**
