### PR TITLE
Replace sprintf with @sprintf and remove sprintf function

### PR DESCRIPTION
**Pull request by ZMAlt**
Related to #1542

### CODE REVIEW

**Comment by joa-quim** [comment]
Thanks for finding this. It looks that MacOS compiler is screwing again. The reason I used that sprintf function was to reduce the number of Any's that @sprintf produces and awfully increase the complains of JET reports. Anyway, you need to fix also the tests at the end of `test_common_opts.jl`

For curiosity, what happens if you run the tests without these sprintf changes?

**Comment by ZMAlt** [comment]
I'll update the tests right now.

Without these changes, the error is similar to #1542 , as follows.

```julia
(@v1.11) pkg> test GMT
     Testing GMT
      Status `/private/var/folders/pz/ygb4st295jqb9453fbyq3mtm0000gn/T/jl_9jULJu/Project.toml`
  [5752ebe1] GMT v1.18.0
  [aea7be01] PrecompileTools v1.2.1
  [08abe8d2] PrettyTables v2.4.0
  [10745b16] Statistics v1.11.1
  [bd369af6] Tables v1.12.0
⌅ [a7073274] GDAL_jll v301.900.0+0
  [b68b8c3f] GMT_jll v6.5.2+2
  [61579ee1] Ghostscript_jll v9.55.0+4
  [58948b4f] PROJ_jll v901.300.0+1
  [ade2ca70] Dates v1.11.0
  [f43a241f] Downloads v1.6.0
  [37e2e46d] LinearAlgebra v1.11.0
  [de0858da] Printf v1.11.0
  [8dfed614] Test v1.11.0
      Status `/private/var/folders/pz/ygb4st295jqb9453fbyq3mtm0000gn/T/jl_9jULJu/Manifest.toml`
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [5752ebe1] GMT v1.18.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.6.0
  [b964fa9f] LaTeXStrings v1.3.1
  [3da0fdf6] MPIPreferences v0.1.11
  [bac558e1] OrderedCollections v1.6.3
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [189a3867] Reexport v1.2.2
  [10745b16] Statistics v1.11.1
  [892a3eda] StringManipulation v0.4.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [8ce61222] Arrow_jll v10.0.0+1
  [0b7ba130] Blosc_jll v1.21.5+0
  [6e34b625] Bzip2_jll v1.0.8+1
  [2e619515] Expat_jll v2.6.2+0
  [f5851436] FFTW_jll v3.3.10+1
⌅ [a7073274] GDAL_jll v301.900.0+0
  [d604d12d] GEOS_jll v3.13.0+0
  [b68b8c3f] GMT_jll v6.5.2+2
  [78b55507] Gettext_jll v0.21.0+0
  [61579ee1] Ghostscript_jll v9.55.0+4
  [7746bdde] Glib_jll v2.80.2+0
  [0951126a] GnuTLS_jll v3.8.4+0
  [0234f1f7] HDF5_jll v1.14.3+3
⌃ [e33a78d0] Hwloc_jll v2.11.1+1
⌅ [a51ab1cf] ICU_jll v69.1.0+0
  [aacddb02] JpegTurbo_jll v3.0.4+0
  [b39eb1a6] Kerberos_krb5_jll v1.19.3+0
  [17f450c3] LAPACK32_jll v3.12.0+0
⌅ [88015f11] LERC_jll v3.0.0+1
  [1d63c593] LLVMOpenMP_jll v18.1.7+0
  [dd4b983a] LZO_jll v2.10.2+1
  [08be9ffa] LibPQ_jll v16.0.0+0
⌅ [e9f186c6] Libffi_jll v3.2.2+1
  [94ce4f54] Libiconv_jll v1.17.0+0
  [4b2f31a3] Libmount_jll v2.40.1+0
⌅ [89763e89] Libtiff_jll v4.5.1+1
  [d3a379c0] LittleCMS_jll v2.16.0+0
  [5ced341a] Lz4_jll v1.10.0+1
  [7cb0a576] MPICH_jll v4.2.2+0
  [f1f71cc9] MPItrampoline_jll v5.5.0+0
  [9237b28f] MicrosoftMPI_jll v10.1.4+2
  [7243133f] NetCDF_jll v400.902.211+1
⌅ [4c82536e] Nettle_jll v3.7.2+0
  [656ef2d0] OpenBLAS32_jll v0.3.28+3
  [643b3616] OpenJpeg_jll v2.5.2+0
⌅ [fe0851c0] OpenMPI_jll v4.1.6+0
  [458c3c95] OpenSSL_jll v3.0.15+1
  [c2071276] P11Kit_jll v0.24.1+0
  [2f80f16e] PCRE_jll v8.45.0+0
  [58948b4f] PROJ_jll v901.300.0+1
  [76ed43ae] SQLite_jll v3.45.3+0
⌅ [e0b8ae26] Thrift_jll v0.16.0+0
  [02c8fc9c] XML2_jll v2.13.3+0
  [ffd25f8a] XZ_jll v5.4.6+0
  [3161d3a3] Zstd_jll v1.5.6+1
⌅ [28df3c45] boost_jll v1.76.0+1
  [477f73a3] libaec_jll v1.1.2+0
  [06c338fa] libgeotiff_jll v100.701.300+0
⌃ [b53b4c65] libpng_jll v1.6.43+1
  [337d8026] libzip_jll v1.10.1+0
⌅ [fe1e1685] snappy_jll v1.1.10+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [781609d7] GMP_jll v6.3.0+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [efcefdf7] PCRE2_jll v10.42.0+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
        Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading.
Precompiling project for configuration --code-coverage=none --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=yes --inline=yes --startup-file=no --track-allocation=none...
  ✗ GMT
  7 dependencies successfully precompiled in 36 seconds. 90 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

GMT --code-coverage=none --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=yes --inline=yes --startup-file=no --track-allocation=none 

Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to "/Users/zm/.julia/compiled/v1.11/GMT/jl_V5q430".
grdimage [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions given in arc degrees, minutes [and seconds]. Use -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected coordinates, with <unit> selected from e|f|k|M|n|u [Default: e]. If +u is set, projected regions centered on (0,0) may be set via -R<halfwidth>[/<halfheight>]+u<unit>, where <halfheight> defaults to <halfwidth> if not given. Use [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]] format for time axes. Append +r if -R specifies the coordinates of the lower left and upper right corners of a rectangular area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and grid dimensions, where <code> is a 2-char combo from [T|M|B][L|C|R] (top/middle/bottom/left/center/right) and grid spacing must be specified via -I<dx>[/<dy>] (also see -r).
grdimage [ERROR]: Offending option -R32/1.976262583365e-323/3.0460966492498e-314/1.976262583365e-323
ERROR: LoadError: Something went wrong when calling the module. GMT error number = 72
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] gmt(::String, ::GMT.GMTgrid{Float32, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/XumeP/src/gmt_main.jl:170
  [3] finish_PS_module(::Dict{Symbol, Any}, ::Vector{String}, ::String, ::Bool, ::Bool, ::Bool, ::GMT.GMTgrid{Float32, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/XumeP/src/common_options.jl:4449
  [4] grdimage(cmd0::String, arg1::Matrix{Float32}, arg2::Nothing, arg3::Nothing; first::Bool, kwargs::@Kwargs{})
    @ GMT ~/.julia/packages/GMT/XumeP/src/grdimage.jl:145
  [5] grdimage
    @ ~/.julia/packages/GMT/XumeP/src/grdimage.jl:51 [inlined]
  [6] grdimage (repeats 2 times)
    @ ~/.julia/packages/GMT/XumeP/src/grdimage.jl:225 [inlined]
  [7] macro expansion
    @ ~/.julia/packages/GMT/XumeP/src/GMT.jl:352 [inlined]
  [8] macro expansion
    @ ~/.julia/packages/PrecompileTools/L8A3n/src/workloads.jl:140 [inlined]
  [9] top-level scope
    @ ~/.julia/packages/GMT/XumeP/src/GMT.jl:332
 [10] include
    @ ./Base.jl:557 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2753
 [12] top-level scope
    @ stdin:4
in expression starting at /Users/zm/.julia/packages/GMT/XumeP/src/GMT.jl:1
in expression starting at stdin:

(@v1.11) pkg> 

```

**Comment by joa-quim** [comment]
OK, at least there is consistency in the failures.

**Comment by ZMAlt** [comment]
By the way, I noticed that you used the merge operation?. If there are multiple commits in a single PR, you can try squashing them to keep the git log clean.

**Pull request merged**
