### PR TITLE
Release the need to use fill and/or pen from main options. Let arrow() set them all.

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by adigitoleo** [comment]
Here's the same plot as in #753 , top left panel is `arrow = (; fill = ... , pen = ...)`

test_arrow_fill

Couple of things:
- stem color is being set, I thought that should only be controlled by `linecolor`?
- stem width setting `linewidth` is ignored for the first three panels

```
Warning: the following options were not consumed in grdvector => [:linewidth]
Warning: the following options were not consumed in grdvector => [:linewidth, :pen]
Warning: the following options were not consumed in grdvector => [:linewidth]
Warning: the following options were not consumed in grdvector => [:pen]
```

Thanks for looking into it. I hope I can dig into the code soon to offer more PRs.

**Comment by joa-quim** [comment]
OK, now ``linecolor`` is take into account **when** no ``pen`` in `arrow()``, Note that there is no ``linecolor`` in ``arrow`` and all settings in ``arrow()`` take precedence over their equivalents in *base* ``grdvector``. Will look into ``linewidth`` tomorrow but should be similar case to ``linecolor``.

**Comment by adigitoleo** [comment]
> now linecolor is take into account when no pen in arrow()

I thought that `arrow(; pen = ...)` sets the _head_ options only though? And GMT 5 vectors have separate stem and head properties (`-W` for stem and `+p` for head), so to be 1:1 with GMT we would need a way to set stem and head properties independently, and I have been using `line{color,width}` for stems.

https://docs.generic-mapping-tools.org/latest/grdvector.html#vector-attributes

**Comment by joa-quim** [comment]
You are write about the different *pens* for stems and heads. I was mislead by the vague description of -W option

> Set pen attributes used for vector outlines [Default: width = default, color = black, style = solid].

So, I restored the ability of setting them separately. You can do
```
grdvector(Gdzdx, Gdzdy, inc=0.3, arrow=(length=0.4, shape=0, stop=true, norm=0.4, pen=(1,"green@0")), linecolor=:blue, lw=2)
```
In the mean time I found 2 bugs in GMT. This doesn't set the stem pen (allowed if arrow head is painted), but uses the arrow head outline for the stem
```
grdvector(Gdzdx, Gdzdy, inc=0.3, arrow=(length=0.4, shape=0, stop=true, norm=0.4, fill=:red, pen=:green)
```
If we don't want the stem the alternatives are to paint it in white, or use transparency. But the transparency for the stem sets it also for the head outline. Even if we try to set a transparency in head outline too. You don't see the head green outline with this.
```
grdvector(Gdzdx, Gdzdy, inc=0.3, arrow=(length=0.4, shape=0, stop=true, norm=0.4, fill=:red, pen=(1,"green@0")), show=1, Vd=1, lc="black@90")
```

**Comment by adigitoleo** [comment]
I see. Yes, I can reproduce this in GMT as well (vector head outline is used for stem unless stem is set with `-W`). I think this is probably the best we can do at the moment.

**Pull request merged**
