### PR TITLE
use VersionParsing to parse non-semver versions

### PR DESCRIPTION
**Pull request by stevengj**
You might want to use the VersionParsing package to parse non-semver versions from external code. 

e.g. I notice that you were manually stopping at underscores, which `vparse` should handle; do you have an example of a version string with an underscore that GMT would return?

### CODE REVIEW

**Comment by joa-quim** [comment]
The GMT master version returns info about the date it was built
```
gmt --version
6.4.0_3f928be_2022.01.21
```
so that bit of code is mostly for me and the few others that might be using a GMT dev version.
I didn't know ``VersionParsing`` and I see that is a real small dependency but do you think it worth adding a dependency, for minute that it is, to replace a one-line instruction?

**Comment by joa-quim** [comment]
Ah, and forgot the most obvious place where GMTdev is used, which is the CI tests. That's very likely why the tests fail in this branch.

**Comment by stevengj** [comment]
In the latest version of VersionParsing, `6.4.0_3f928be_2022.01.21` should be parsed as `v"6.4.0-3f928be-2022.01.21"`.

If you know that the versions always have this format, of course, it's totally fine to parse it yourselves.  My general principle is that one can't trust non-semver version numbers to follow a particular format, so it's good to try to build a centralized robust non-semver parser.

**Comment by joa-quim** [comment]
Since I'm also a GMT developer it's pretty save to expect that the format will not change without that been taken care here. And again, that version format is only for ``dev`` versions. Official releases follow the semver format.

Glad that it helped and thanks for having looked at this.

**Pull request closed without merging**
